FROM quay.io/keycloak/keycloak:latest as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mysql

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

WORKDIR /opt/keycloak
COPY --chown=keycloak:keycloak --chmod=644 keycloak.nfs.info.p12 conf/
COPY --chown=keycloak:keycloak --chmod=644 keycloak.conf conf/
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
